---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-route  
  labels:
    app.kubernetes.io/name: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`traefik.localhost`) 
    kind: Rule
    services:
      - kind: TraefikService
        name: api@internal

