---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: components
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-components
  annotations:
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-components
  ports:
  - port: 80
    name: "web"
    targetPort: web
    protocol: TCP
    nodePort: 30080
  - port: 443
    name: "websecure"
    targetPort: websecure
    protocol: TCP
    nodePort: 30443

