kind: Component
apiVersion: bbr.k8s.io/v1alpha1
metadata:
  name: sealed-secrets
helm:
  repo: sealed-secrets
  repo-url: https://bitnami-labs.github.io/sealed-secrets
  version: v2.17.1
  chart: sealed-secrets/sealed-secrets
  post-init:
    renames:
      - original: bitnami.com_sealedsecrets.yaml
        renamed: crd.yaml
