apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ns.yaml
- ./rbac/serviceaccount.yaml
- ./rbac/clusterrole.yaml
- ./rbac/clusterrolebinding.yaml
- ./deployment.yaml
- ./ingressclass.yaml
# - ./prometheusrules.yaml 
- ./service-metrics.yaml
- ./servicemonitor.yaml

patches:
- target:
    kind: ServiceMonitor
    name: ".*"
  patch: |-
    - op: add
      path: /metadata/labels/release
      value: prometheus
